[package]
name = "snare_script"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { version="0.11.5", features=["lua54"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
